Repository leonlatsch/Photok, pull requests merged in 2021-01, with the labels that each got.

#38 Migrate to official plugin for OSS licenses
  CONTRIBUTORS
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/dev/leonlatsch/photok/ui/components/Dialogs.kt
  app/src/main/java/dev/leonlatsch/photok/ui/settings/AboutFragment.kt
  app/src/main/res/values/styles.xml
  build.gradle
Labels: enhancement

#40 Migrate to Gradle Kotlin DSL
  app/build.gradle
  app/build.gradle.kts
  app/proguard-rules.pro
  build.gradle
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle
  settings.gradle.kts
Labels: enhancement

#52 Feature: Hide App
  CHANGELOG.md
  app/src/main/AndroidManifest.xml
  app/src/main/java/dev/leonlatsch/photok/DialLauncher.kt
  app/src/main/java/dev/leonlatsch/photok/di/AppModule.kt
  app/src/main/java/dev/leonlatsch/photok/di/DaggerBroadcastReceiver.kt
  app/src/main/java/dev/leonlatsch/photok/settings/Config.kt
  app/src/main/java/dev/leonlatsch/photok/ui/MainActivity.kt
  app/src/main/java/dev/leonlatsch/photok/ui/backup/UnlockBackupDialogFragment.kt
  app/src/main/java/dev/leonlatsch/photok/ui/backup/ValidateBackupDialogFragment.kt
  app/src/main/java/dev/leonlatsch/photok/ui/components/base/BaseActivity.kt
  app/src/main/java/dev/leonlatsch/photok/ui/components/base/BaseDialogFragment.kt
  app/src/main/java/dev/leonlatsch/photok/ui/components/bindings/Bindable.kt
  app/src/main/java/dev/leonlatsch/photok/ui/components/bindings/BindableActivity.kt
  app/src/main/java/dev/leonlatsch/photok/ui/components/bindings/BindableBottomSheetDialogFragment.kt
  app/src/main/java/dev/leonlatsch/photok/ui/components/bindings/BindableDialogFragment.kt
  app/src/main/java/dev/leonlatsch/photok/ui/components/bindings/BindableFragment.kt
  app/src/main/java/dev/leonlatsch/photok/ui/components/bindings/ObservableViewModel.kt
  app/src/main/java/dev/leonlatsch/photok/ui/gallery/GalleryFragment.kt
  app/src/main/java/dev/leonlatsch/photok/ui/process/base/BaseProcessBottomSheetDialogFragment.kt
  app/src/main/java/dev/leonlatsch/photok/ui/settings/AboutFragment.kt
  app/src/main/java/dev/leonlatsch/photok/ui/settings/SettingsFragment.kt
  app/src/main/java/dev/leonlatsch/photok/ui/settings/changepassword/ChangePasswordDialog.kt
  app/src/main/java/dev/leonlatsch/photok/ui/settings/credits/CreditsAdapter.kt
  app/src/main/java/dev/leonlatsch/photok/ui/settings/credits/CreditsFragment.kt
  app/src/main/java/dev/leonlatsch/photok/ui/settings/hideapp/ForwardDialerActivity.kt
  app/src/main/java/dev/leonlatsch/photok/ui/settings/hideapp/ToggleAppVisibilityDialog.kt
  app/src/main/java/dev/leonlatsch/photok/ui/settings/hideapp/ToggleAppVisibilityViewModel.kt
  app/src/main/java/dev/leonlatsch/photok/ui/setup/SetupFragment.kt
  app/src/main/java/dev/leonlatsch/photok/ui/start/onboarding/OnBoardingFragment.kt
  app/src/main/java/dev/leonlatsch/photok/ui/unlock/UnlockFragment.kt
  app/src/main/java/dev/leonlatsch/photok/ui/viewphoto/DetailsBottomSheetDialog.kt
  app/src/main/java/dev/leonlatsch/photok/ui/viewphoto/ViewPhotoActivity.kt
  app/src/main/res/drawable/ic_app_blocking.xml
  app/src/main/res/drawable/ic_arrow_forward.xml
  app/src/main/res/drawable/ic_dialpad.xml
  app/src/main/res/drawable/ic_phone.xml
  app/src/main/res/layout/dialog_edit_text_preference_secret_code.xml
  app/src/main/res/layout/dialog_fragment_hide_app.xml
  app/src/main/res/layout/dialog_fragment_show_app.xml
  app/src/main/res/layout/dialog_toggle_app_visibility.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/settings.xml
Labels: feature

#63 Update Chinese Strings
  app/src/main/res/values-zh-rCN/strings.xml
Labels: improvement

#65 Feature: New Toolbar
  app/src/main/java/dev/leonlatsch/photok/ui/MainActivity.kt
  app/src/main/java/dev/leonlatsch/photok/ui/viewphoto/ViewPhotoActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_view_photo.xml
  app/src/main/res/layout/fragment_gallery.xml
  app/src/main/res/layout/preference_layout_template.xml
  app/src/main/res/values/styles.xml
Labels: improvement

#71 Update a single german string
  app/src/main/res/values-de/strings.xml
Labels: improvement
