Repository leonlatsch/Photok, pull requests merged in 2021-08, with the labels that each got.

#127 Change Icon
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/ic_launcher_orig.xml
  app/src/main/res/layout/dialog_fragment_hide_app.xml
  app/src/main/res/layout/dialog_fragment_show_app.xml
  app/src/main/res/layout/fragment_about.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: task

#129 Finish Release 1.3.3
  .github/workflows/create-rc.yml
  CHANGELOG.md
  app/src/main/java/dev/leonlatsch/photok/other/extensions/WindowExtensions.kt
  gradle.properties
Labels: release

#132 Dutch Translation
  app/src/main/res/values-nl/strings.xml
Labels: technical

#138 Finish Release 1.3.4
  CHANGELOG.md
  app/src/main/java/dev/leonlatsch/photok/settings/ui/hideapp/ToggleAppVisibilityViewModel.kt
  app/src/main/res/layout/dialog_toggle_app_visibility.xml
  gradle.properties
Labels: release

#140 change links in readme
  README.md
Labels: task

#144 Feature/#143 App Icon Rework
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/ic_launcher_background.xml
Labels: improvement
