Repository leonlatsch/Photok, pull requests merged in 2022-09, with the labels that each got.

#186 Update Chinese Strings
  README.md
  app/src/main/res/values-zh-rCN/strings.xml
Labels: sighted

#187 Fix Double Import from Sharing System
  app/src/main/java/dev/leonlatsch/photok/di/AppModule.kt
  app/src/main/java/dev/leonlatsch/photok/gallery/ui/importing/SharedUrisStore.kt
  app/src/main/java/dev/leonlatsch/photok/main/ui/MainActivity.kt
  app/src/main/java/dev/leonlatsch/photok/main/ui/MainViewModel.kt
Labels: bug

#190 Add french translations
  app/src/main/assets/contributors.json
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
Labels: translation, sighted
