Repository leonlatsch/Photok, pull requests merged in 2024-08, with the labels that each got.

#348 Allow install on external SD
  app/src/main/AndroidManifest.xml
Labels: technical, improvement

#329 Get rid of glide & move thumbnail related logic to separate class
  app/build.gradle.kts
  app/src/main/java/dev/leonlatsch/photok/backup/domain/RestoreBackupV1.kt
  app/src/main/java/dev/leonlatsch/photok/di/AppModule.kt
  app/src/main/java/dev/leonlatsch/photok/model/io/CreateThumbnailUseCase.kt
  app/src/main/java/dev/leonlatsch/photok/model/repositories/PhotoRepository.kt
Labels: technical

#357 Refactor thumbnail creation and increase size to 256
  app/src/main/java/dev/leonlatsch/photok/backup/domain/RestoreBackupV1.kt
  app/src/main/java/dev/leonlatsch/photok/di/AppModule.kt
  app/src/main/java/dev/leonlatsch/photok/model/io/CreateThumbnailsUseCase.kt
  app/src/main/java/dev/leonlatsch/photok/model/repositories/PhotoRepository.kt
Labels: technical, improvement

#358 allow importing webm video files
  app/src/main/java/dev/leonlatsch/photok/model/database/entity/PhotoType.kt
  app/src/main/java/dev/leonlatsch/photok/model/repositories/PhotoRepository.kt
Labels: feature

#360 [Bug] Fix Video Previews
  app/src/main/java/dev/leonlatsch/photok/imageloading/data/ImageStorageImpl.kt
  app/src/main/java/dev/leonlatsch/photok/imageloading/di/ImageLoadingModule.kt
  app/src/main/java/dev/leonlatsch/photok/imageloading/domain/ImageStorage.kt
  app/src/main/java/dev/leonlatsch/photok/model/io/CreateThumbnailsUseCase.kt
  app/src/main/java/dev/leonlatsch/photok/other/extensions/BitmapExtensions.kt
Labels: bug

#365 Finish Release 1.7.4
  app/src/main/assets/open_source_licenses.json
  gradle.properties
Labels: release
