Repository leonlatsch/Photok, pull requests merged in 2024-06, with the labels that each got.

#317 Replace zoomable image library
  app/build.gradle.kts
  app/src/main/java/dev/leonlatsch/photok/gallery/albums/data/AlbumRepositoryImpl.kt
  app/src/main/java/dev/leonlatsch/photok/gallery/albums/domain/AlbumRepository.kt
  app/src/main/java/dev/leonlatsch/photok/imageloading/compose/EncryptedImagePainter.kt
  app/src/main/java/dev/leonlatsch/photok/imageviewer/ui/ImageViewerFragment.kt
  app/src/main/java/dev/leonlatsch/photok/imageviewer/ui/ImageViewerViewModel.kt
  app/src/main/java/dev/leonlatsch/photok/imageviewer/ui/PhotoPagerAdapter.kt
  app/src/main/java/dev/leonlatsch/photok/imageviewer/ui/PhotoViewHolder.kt
  app/src/main/java/dev/leonlatsch/photok/imageviewer/ui/compose/PhotoViewHolderContent.kt
  app/src/main/java/dev/leonlatsch/photok/model/database/dao/AlbumDao.kt
  app/src/main/java/dev/leonlatsch/photok/model/database/dao/PhotoDao.kt
  app/src/main/java/dev/leonlatsch/photok/model/repositories/PhotoRepository.kt
  app/src/main/res/layout/view_photo_item.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug, improvement

#320 Finish Release 1.7.1
  app/src/main/assets/open_source_licenses.json
  app/src/main/java/dev/leonlatsch/photok/model/database/dao/AlbumDao.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/strings.xml
  gradle.properties
Labels: release

#332 Update spanish translation
  app/src/main/res/values-es/strings.xml
Labels: translation

#336 Implement playing gifs with coil
  app/build.gradle.kts
  app/src/main/java/dev/leonlatsch/photok/imageloading/di/ImageLoadingModule.kt
Labels: improvement
