Repository leonlatsch/Photok, pull requests merged in 2024-07, with the labels that each got.

#339 Fix: Error when loading sampled images
  app/src/main/java/dev/leonlatsch/photok/imageloading/compose/EncryptedImageFetcher.kt
  app/src/main/java/dev/leonlatsch/photok/imageloading/compose/EncryptedImageFetcherFactory.kt
Labels: bug

#342 TECH: Refactor app state
  app/src/main/java/dev/leonlatsch/photok/BaseApplication.kt
  app/src/main/java/dev/leonlatsch/photok/main/ui/MainActivity.kt
  app/src/main/java/dev/leonlatsch/photok/other/extensions/ActivityExtensions.kt
  app/src/main/java/dev/leonlatsch/photok/other/extensions/FragmentExtensions.kt
  app/src/main/java/dev/leonlatsch/photok/setup/ui/SetupFragment.kt
  app/src/main/java/dev/leonlatsch/photok/unlock/ui/UnlockFragment.kt
Labels: technical

#344 Add Turkish language support
  app/src/main/res/values-tr/strings.xml
Labels: translation

#346 Finish release 1.7.3
  gradle.properties
Labels: release
