Repository leonlatsch/Photok, pull requests merged in 2025-02, with the labels that each got.

#407 Improve album database performance
  app/schemas/dev.leonlatsch.photok.model.database.PhotokDatabase/3.json
  app/src/main/java/dev/leonlatsch/photok/model/database/PhotokDatabase.kt
  app/src/main/java/dev/leonlatsch/photok/model/database/ref/AlbumPhotoRelation.kt
Labels: technical, improvement

#408 New Import / Fab Menu that uses Photo Picker
  app/src/main/java/dev/leonlatsch/photok/gallery/albums/detail/ui/AlbumDetailNavigator.kt
  app/src/main/java/dev/leonlatsch/photok/gallery/albums/detail/ui/AlbumDetailUiEvent.kt
  app/src/main/java/dev/leonlatsch/photok/gallery/albums/detail/ui/AlbumDetailViewModel.kt
  app/src/main/java/dev/leonlatsch/photok/gallery/albums/detail/ui/compose/AlbumDetailContent.kt
  app/src/main/java/dev/leonlatsch/photok/gallery/ui/GalleryUiEvent.kt
  app/src/main/java/dev/leonlatsch/photok/gallery/ui/GalleryViewModel.kt
  app/src/main/java/dev/leonlatsch/photok/gallery/ui/components/ImportMenuBottomSheet.kt
  app/src/main/java/dev/leonlatsch/photok/gallery/ui/components/PhotoGallery.kt
  app/src/main/java/dev/leonlatsch/photok/gallery/ui/compose/GalleryContent.kt
  app/src/main/java/dev/leonlatsch/photok/gallery/ui/compose/GalleryPlaceholder.kt
  app/src/main/java/dev/leonlatsch/photok/gallery/ui/compose/GalleryScreen.kt
  app/src/main/java/dev/leonlatsch/photok/gallery/ui/importing/ImportMenuDialog.kt
  app/src/main/java/dev/leonlatsch/photok/gallery/ui/navigation/GalleryNavigationEvent.kt
  app/src/main/java/dev/leonlatsch/photok/gallery/ui/navigation/GalleryNavigator.kt
  app/src/main/java/dev/leonlatsch/photok/gallery/ui/navigation/PhotoActionsNavigator.kt
  app/src/main/java/dev/leonlatsch/photok/settings/ui/compose/ConfigCompositionLocal.kt
  app/src/main/java/dev/leonlatsch/photok/ui/components/MagicFab.kt
  app/src/main/java/dev/leonlatsch/photok/ui/theme/Color.kt
  app/src/main/java/dev/leonlatsch/photok/uicomponnets/Chooser.kt
  app/src/main/res/drawable/ic_camera.xml
  app/src/main/res/layout/dialog_import_menu.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
Labels: improvement

#379 Dismiss progress dialogs when done
  app/src/main/java/dev/leonlatsch/photok/uicomponnets/base/processdialogs/BaseProcessBottomSheetDialogFragment.kt
Labels: improvement

#415 Tech: Remove OssLicenseView and just display a html report for ThirdPartyLicenses
  app/build.gradle.kts
  app/src/main/assets/open_source_licenses.html
  app/src/main/assets/open_source_licenses.json
  app/src/main/java/dev/leonlatsch/photok/settings/ui/thirdparty/OssLicensesFragment.kt
  app/src/main/res/layout/fragment_oss_licenses.xml
Labels: technical

#418 Fix: Only use photo picker when not using "Delete imported files"
  app/src/main/java/dev/leonlatsch/photok/gallery/ui/components/ImportMenuBottomSheet.kt
  app/src/main/java/dev/leonlatsch/photok/gallery/ui/importing/ImportBottomSheetDialogFragment.kt
  app/src/main/java/dev/leonlatsch/photok/gallery/ui/importing/ImportViewModel.kt
  app/src/main/java/dev/leonlatsch/photok/model/repositories/PhotoRepository.kt
  app/src/main/java/dev/leonlatsch/photok/uicomponnets/base/processdialogs/BaseProcessBottomSheetDialogFragment.kt
Labels: technical

#419 Bug: Fix crash with very big images
  app/src/main/java/dev/leonlatsch/photok/imageloading/compose/EncryptedImageFetcher.kt
  app/src/main/java/dev/leonlatsch/photok/imageloading/compose/EncryptedImageFetcherFactory.kt
  app/src/main/java/dev/leonlatsch/photok/imageloading/di/ImageLoadingModule.kt
  app/src/main/java/dev/leonlatsch/photok/other/extensions/WindowExtensions.kt
Labels: bug

#421 Finish Release 1.9.0
  README.md
  app/src/main/assets/open_source_licenses.html
  app/src/main/java/dev/leonlatsch/photok/gallery/ui/components/ImportMenuBottomSheet.kt
  app/src/main/java/dev/leonlatsch/photok/gallery/ui/components/PhotoGallery.kt
  app/src/main/java/dev/leonlatsch/photok/news/newfeatures/ui/NewFeaturesDialog.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
  gradle.properties
Labels: release

#427 Fix: ANR in Albums and fully image screen.
  app/src/main/java/dev/leonlatsch/photok/imageloading/compose/EncryptedImageFetcher.kt
Labels: bug

#428 Fix Label Magic Fab label for new album
  app/src/main/java/dev/leonlatsch/photok/gallery/albums/ui/compose/AlbumsContent.kt
  app/src/main/java/dev/leonlatsch/photok/gallery/albums/ui/compose/AlbumsPlaceholder.kt
  app/src/main/java/dev/leonlatsch/photok/gallery/ui/components/PhotoGallery.kt
  app/src/main/java/dev/leonlatsch/photok/gallery/ui/compose/GalleryPlaceholder.kt
  app/src/main/java/dev/leonlatsch/photok/ui/components/MagicFab.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug

#431 Fix crash when getting file name without permission
  app/src/main/java/dev/leonlatsch/photok/other/Utils.kt
Labels: bug

#438 Fix: Crash when opening external file
  app/src/main/java/dev/leonlatsch/photok/model/io/EncryptedStorageManager.kt
Labels: bug

#437 Fix: Crash when hide keyboard in setup and unlock
  app/src/main/java/dev/leonlatsch/photok/other/extensions/FragmentExtensions.kt
  app/src/main/java/dev/leonlatsch/photok/setup/ui/SetupFragment.kt
  app/src/main/java/dev/leonlatsch/photok/unlock/ui/UnlockFragment.kt
Labels: bug

#440 Finish Release 1.9.2
  gradle.properties
Labels: release
