Repository leonlatsch/Photok, pull requests merged in 2025-03, with the labels that each got.

#443 Fix crashes and ANRs
  app/src/main/java/dev/leonlatsch/photok/gallery/albums/ui/navigation/AlbumsNavigator.kt
  app/src/main/java/dev/leonlatsch/photok/imageloading/compose/EncryptedImageFetcher.kt
  app/src/main/java/dev/leonlatsch/photok/imageloading/di/ImageLoadingModule.kt
  app/src/main/java/dev/leonlatsch/photok/setup/ui/SetupFragment.kt
  app/src/main/java/dev/leonlatsch/photok/unlock/ui/UnlockFragment.kt
  app/src/main/res/navigation/main_nav_graph.xml
Labels: bug

#445 Fix: Auto Lock timer when choosing files and directories
  app/src/main/java/dev/leonlatsch/photok/gallery/ui/components/ImportMenuBottomSheet.kt
  app/src/main/java/dev/leonlatsch/photok/gallery/ui/components/PhotoGallery.kt
  app/src/main/java/dev/leonlatsch/photok/imageviewer/ui/ImageViewerFragment.kt
  app/src/main/java/dev/leonlatsch/photok/other/extensions/Extensions.kt
  app/src/main/java/dev/leonlatsch/photok/other/extensions/FragmentExtensions.kt
  app/src/main/java/dev/leonlatsch/photok/settings/ui/SettingsFragment.kt
Labels: bug

#447 Finish release 1.9.3
  gradle.properties
Labels: release

#452 Add Password Check before Resetting App (#248)
  app/src/main/java/dev/leonlatsch/photok/settings/ui/SettingsFragment.kt
  app/src/main/java/dev/leonlatsch/photok/settings/ui/checkpassword/CheckPasswordDialog.kt
  app/src/main/java/dev/leonlatsch/photok/settings/ui/checkpassword/CheckPasswordState.kt
  app/src/main/java/dev/leonlatsch/photok/settings/ui/checkpassword/CheckPasswordViewModel.kt
  app/src/main/res/layout/dialog_check_password.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature
